const analyticsEndpoint=window.RESEARCH_ANALYTICS_ENDPOINT||'';
const consentKey='research-library-analytics-consent';
function analyticsConsent(){try{return localStorage.getItem(consentKey)==='yes'}catch{return false}}
function analyticsId(){let id=localStorage.getItem('research-library-analytics-id');if(!id){id=crypto.randomUUID();localStorage.setItem('research-library-analytics-id',id)}return id}
async function recordAnalytics(event){if(!analyticsEndpoint||!analyticsConsent())return;try{await fetch(analyticsEndpoint.replace(/\/$/,'')+'/event',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(event),keepalive:true})}catch{}}
function analyticsPaper(p){return {kind:'click',paper_key:(p.doi||p.title||'unknown').slice(0,150).toLowerCase(),title:(p.title||'Untitled').slice(0,300),doi:(p.doi||'').slice(0,150),cluster:(p.cluster||p.topics?.[0]||'Other research').slice(0,100)}}
function trackPaper(p,action){recordAnalytics({...analyticsPaper(p),action})}
function initAnalytics(){if(!analyticsEndpoint)return;const banner=document.createElement('aside');banner.className='analytics-choice';banner.setAttribute('aria-label','Analytics choice');banner.innerHTML='<span>Help us count visits and links opened. With your permission, we count an approximate daily browser visit and paper-link clicks. No search terms, IP addresses, or publisher activity are stored by this site.</span> ';const yes=document.createElement('button');yes.textContent='Allow analytics';const no=document.createElement('button');no.textContent='Decline';no.className='quiet';yes.addEventListener('click',()=>{localStorage.setItem(consentKey,'yes');banner.remove();recordAnalytics({kind:'visit',visitor:analyticsId()})});no.addEventListener('click',()=>{localStorage.setItem(consentKey,'no');banner.remove()});banner.append(yes,no);if(analyticsConsent())recordAnalytics({kind:'visit',visitor:analyticsId()});else if(!localStorage.getItem(consentKey))document.body.append(banner)}
initAnalytics();
